server:
  port: 8083
spring:
  application:
    name: cloud-other
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka/